
export const PERMISSIONS = {
  // General
  DASHBOARD_VIEW: 'dashboard:view',

  // Operations
  OPERATIONS_VIEW: 'operations:view',
  FARM_MAP_VIEW: 'farmmap:view',
  OPERATIONAL_CALENDAR_VIEW: 'calendar:view',
  SITES_VIEW: 'sites:view',
  SITES_MANAGE: 'sites:manage',
  SEAWEED_TYPES_VIEW: 'seaweed_types:view',
  SEAWEED_TYPES_MANAGE: 'seaweed_types:manage',
  MODULES_VIEW: 'modules:view',
  MODULES_MANAGE: 'modules:manage',
  CUTTING_OPERATIONS_VIEW: 'cutting_operations:view',
  CUTTING_OPERATIONS_MANAGE: 'cutting_operations:manage',
  CUTTINGS_LEDGER_VIEW: 'cuttings_ledger:view',
  CYCLES_VIEW: 'cycles:view',
  CYCLES_MANAGE: 'cycles:manage',
  HARVESTING_VIEW: 'harvesting:view',
  HARVESTING_MANAGE: 'harvesting:manage',
  DRYING_VIEW: 'drying:view',
  DRYING_MANAGE: 'drying:manage',
  BAGGING_VIEW: 'bagging:view',
  BAGGING_MANAGE: 'bagging:manage',

  // Inventory
  INVENTORY_VIEW: 'inventory:view',
  INVENTORY_MANAGE_ON_SITE: 'inventory:manage:on_site',
  INVENTORY_MANAGE_DELIVERIES: 'inventory:manage:deliveries',
  INVENTORY_MANAGE_TRANSFERS: 'inventory:manage:transfers',
  INVENTORY_MANAGE_WAREHOUSE: 'inventory:manage:warehouse',
  EXPORTS_VIEW: 'exports:view',
  EXPORTS_MANAGE: 'exports:manage',

  // Stakeholders & Payments
  STAKEHOLDERS_VIEW: 'stakeholders:view',
  FARMERS_VIEW: 'farmers:view',
  FARMERS_MANAGE: 'farmers:manage',
  EMPLOYEES_VIEW: 'employees:view',
  EMPLOYEES_MANAGE: 'employees:manage',
  PROVIDERS_VIEW: 'providers:view',
  PROVIDERS_MANAGE: 'providers:manage',
  CREDITS_VIEW: 'credits:view',
  CREDITS_MANAGE: 'credits:manage',
  PAYMENTS_VIEW: 'payments:view',
  PAYMENTS_MANAGE: 'payments:manage',
  PAYROLL_VIEW: 'payroll:view',
  PAYROLL_MANAGE: 'payroll:manage',

  // Monitoring
  MONITORING_VIEW: 'monitoring:view',
  TESTS_VIEW: 'tests:view',
  TESTS_MANAGE: 'tests:manage',
  INCIDENTS_VIEW: 'incidents:view',
  INCIDENTS_MANAGE: 'incidents:manage',
  GALLERY_VIEW: 'gallery:view',
  GALLERY_MANAGE: 'gallery:manage',

  // Reports
  REPORTS_VIEW: 'reports:view',

  // Settings
  SETTINGS_VIEW: 'settings:view',
  SETTINGS_GENERAL_MANAGE: 'settings:general:manage',
  USERS_VIEW: 'users:view',
  USERS_INVITE: 'users:invite',
  ROLES_VIEW: 'roles:view',
  ROLES_MANAGE: 'roles:manage',
  INCIDENT_SETTINGS_MANAGE: 'settings:incidents:manage',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

export const PERMISSION_GROUPS: { name: string, permissions: { id: Permission, label: string }[] }[] = [
    { name: 'Dashboard', permissions: [{ id: PERMISSIONS.DASHBOARD_VIEW, label: 'View Dashboard' }] },
    { name: 'Operations', permissions: [
        { id: PERMISSIONS.OPERATIONS_VIEW, label: 'View Operations Menu' },
        { id: PERMISSIONS.FARM_MAP_VIEW, label: 'View Farm Map' },
        { id: PERMISSIONS.OPERATIONAL_CALENDAR_VIEW, label: 'View Calendar' },
        { id: PERMISSIONS.SITES_VIEW, label: 'View Sites' },
        { id: PERMISSIONS.SITES_MANAGE, label: 'Manage Sites' },
        { id: PERMISSIONS.SEAWEED_TYPES_VIEW, label: 'View Seaweed Types' },
        { id: PERMISSIONS.SEAWEED_TYPES_MANAGE, label: 'Manage Seaweed Types' },
        { id: PERMISSIONS.MODULES_VIEW, label: 'View Modules' },
        { id: PERMISSIONS.MODULES_MANAGE, label: 'Manage Modules' },
        { id: PERMISSIONS.CUTTING_OPERATIONS_VIEW, label: 'View Cutting Operations' },
        { id: PERMISSIONS.CUTTING_OPERATIONS_MANAGE, label: 'Manage Cutting Operations' },
        { id: PERMISSIONS.CUTTINGS_LEDGER_VIEW, label: 'View Cuttings Ledger' },
        { id: PERMISSIONS.CYCLES_VIEW, label: 'View Cultivation Cycles' },
        { id: PERMISSIONS.CYCLES_MANAGE, label: 'Manage Cultivation Cycles' },
        { id: PERMISSIONS.HARVESTING_VIEW, label: 'View Harvesting' },
        { id: PERMISSIONS.HARVESTING_MANAGE, label: 'Manage Harvesting' },
        { id: PERMISSIONS.DRYING_VIEW, label: 'View Drying' },
        { id: PERMISSIONS.DRYING_MANAGE, label: 'Manage Drying' },
        { id: PERMISSIONS.BAGGING_VIEW, label: 'View Bagging' },
        { id: PERMISSIONS.BAGGING_MANAGE, label: 'Manage Bagging' },
    ]},
    { name: 'Inventory', permissions: [
        { id: PERMISSIONS.INVENTORY_VIEW, label: 'View Inventory Menu' },
        { id: PERMISSIONS.INVENTORY_MANAGE_ON_SITE, label: 'Manage On-Site Storage' },
        { id: PERMISSIONS.INVENTORY_MANAGE_DELIVERIES, label: 'Manage Farmer Deliveries' },
        { id: PERMISSIONS.INVENTORY_MANAGE_TRANSFERS, label: 'Manage Site Transfers' },
        { id: PERMISSIONS.INVENTORY_MANAGE_WAREHOUSE, label: 'Manage Pressing Warehouse' },
        { id: PERMISSIONS.EXPORTS_VIEW, label: 'View Exports' },
        { id: PERMISSIONS.EXPORTS_MANAGE, label: 'Manage Exports' },
    ]},
    { name: 'Stakeholders & Payments', permissions: [
        { id: PERMISSIONS.STAKEHOLDERS_VIEW, label: 'View Stakeholders Menu' },
        { id: PERMISSIONS.FARMERS_VIEW, label: 'View Farmers' },
        { id: PERMISSIONS.FARMERS_MANAGE, label: 'Manage Farmers' },
        { id: PERMISSIONS.EMPLOYEES_VIEW, label: 'View Employees' },
        { id: PERMISSIONS.EMPLOYEES_MANAGE, label: 'Manage Employees' },
        { id: PERMISSIONS.PROVIDERS_VIEW, label: 'View Service Providers' },
        { id: PERMISSIONS.PROVIDERS_MANAGE, label: 'Manage Service Providers' },
        { id: PERMISSIONS.CREDITS_VIEW, label: 'View Farmer Credits' },
        { id: PERMISSIONS.CREDITS_MANAGE, label: 'Manage Farmer Credits' },
        { id: PERMISSIONS.PAYMENTS_VIEW, label: 'View Payments' },
        { id: PERMISSIONS.PAYMENTS_MANAGE, label: 'Manage Payments' },
        { id: PERMISSIONS.PAYROLL_VIEW, label: 'View Payroll' },
        { id: PERMISSIONS.PAYROLL_MANAGE, label: 'Manage Payroll' },
    ]},
    { name: 'Monitoring', permissions: [
        { id: PERMISSIONS.MONITORING_VIEW, label: 'View Monitoring Menu' },
        { id: PERMISSIONS.TESTS_VIEW, label: 'View Periodic Tests' },
        { id: PERMISSIONS.TESTS_MANAGE, label: 'Manage Periodic Tests' },
        { id: PERMISSIONS.INCIDENTS_VIEW, label: 'View Incidents' },
        { id: PERMISSIONS.INCIDENTS_MANAGE, label: 'Manage Incidents' },
        { id: PERMISSIONS.GALLERY_VIEW, label: 'View Photo Gallery' },
        { id: PERMISSIONS.GALLERY_MANAGE, label: 'Manage Photo Gallery' },
    ]},
    { name: 'Reports', permissions: [{ id: PERMISSIONS.REPORTS_VIEW, label: 'View Reports' }] },
    { name: 'Settings', permissions: [
        { id: PERMISSIONS.SETTINGS_VIEW, label: 'View Settings Menu' },
        { id: PERMISSIONS.SETTINGS_GENERAL_MANAGE, label: 'Manage General Settings' },
        { id: PERMISSIONS.USERS_VIEW, label: 'View Users' },
        { id: PERMISSIONS.USERS_INVITE, label: 'Invite New Users' },
        { id: PERMISSIONS.ROLES_VIEW, label: 'View Roles' },
        { id: PERMISSIONS.ROLES_MANAGE, label: 'Manage Roles & Permissions' },
        { id: PERMISSIONS.INCIDENT_SETTINGS_MANAGE, label: 'Manage Incident Settings' },
    ]},
];
